### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Deguang** [Deguang/keep-scroll-sync#1]
- [x] Update to mainfest_verison 3. 
- [ ] Optimize scroll popup reminder.  优化滚动弹窗提示
- [ ] To-read list. 待读列表
- [ ] International(option, at least support Chinese). 多语言支持
